# Generated by Django 3.2.4 on 2021-07-24 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authorname',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='bookname',
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='expirydate',
            field=models.DateField(default=datetime.datetime(2021, 7, 24, 19, 13, 20, 26158)),
        ),
    ]
