# Generated by Django 3.2.4 on 2021-07-25 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_alter_issuedbook_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expirydate',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 18, 34, 28, 914047)),
        ),
    ]
