# Generated by Django 3.2.4 on 2021-07-25 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_alter_issuedbook_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expirydate',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 21, 55, 46, 962640)),
        ),
    ]
