# Generated by Django 3.2.4 on 2021-07-30 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0008_alter_issuedbook_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expirydate',
            field=models.DateField(default=datetime.datetime(2021, 8, 14, 7, 20, 8, 136307)),
        ),
    ]
