# Generated by Django 3.2.4 on 2021-08-01 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0009_alter_issuedbook_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expirydate',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 18, 31, 57, 809972)),
        ),
    ]
