# Generated by Django 3.2.4 on 2021-07-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=40)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('dateofbirth', models.CharField(default='', max_length=40)),
                ('city', models.CharField(default='', max_length=40)),
                ('phone', models.IntegerField(default='', max_length=40)),
                ('is_verify', models.BooleanField(default=False)),
            ],
        ),
    ]
