# Generated by Django 3.2.4 on 2021-07-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_admission',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
