# Generated by Django 3.2.4 on 2021-07-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contactno',
            new_name='contact_no',
        ),
    ]
